Feat/home page search
AngelinaBz/train-a pull request #15
Opened 2024-08-24 11:37 UTC by kvaker

U.P. (HomePage) Create Search section and Filter
[#4](https://github.com/AngelinaBz/train-a/issues/4)

![image](https://github.com/user-attachments/assets/acb6af9e-9652-4d56-9658-f99e01db25bf)

Search Form:

Implement a field for the initial city with autofill.

Implement a field for the final city with autofill.

Implement a field for selecting a date (optional: time) with a calendar.

Implement a form submission button that will be active only if all fields are valid.

2024-08-25 11:28 UTC, AngelinaBz commented
поменяй, пожалуйста, ветку с main на release, если она готова к ревью

2024-08-25 13:21 UTC, MaruyYak commented
1. Мы обговорили архитектуру приложения и папка features в нее не входила, рекомендую перенести страницу home  в папку shared/pages 
2. В сервисе должен быть только сервис, используемые интерфейсы рекомендую вынести в отдельную папку models или types 
3. поправь, пожалуйста, размеры, и опять же таки адаптив
![image](https://github.com/user-attachments/assets/3d29db2d-749b-4508-986b-20e446d100ac)
4. с точки зрения UI очень не аккуратно оформлены инпуты и очистка
![image](https://github.com/user-attachments/assets/1daa5c1c-3a0b-4bd6-b6e1-0c2cc0fac590)
Тоже UI часть, выровняй, пожалуйста, инпуты и лэйблы соответсвующим образом
![image](https://github.com/user-attachments/assets/78f8f781-779c-4317-8401-1900482f6ad8)
5. Не реализована проверка при выборе прошлых дат
 [The user must be able to select a date from a calendar that only allows future days.](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/train-a/search.md#:~:text=The%20user%20must%20be%20able%20to%20select%20a%20date%20from%20a%20calendar%20that%20only%20allows%20future%20days.)

2024-08-27 10:54 UTC, FYMG commented on train-a/src/app/shared/services/search.service.ts
> +    return this.http.get<SearchResult>(this.apiUrl, { params }).pipe(
Используй redux c effect пример #16

2024-08-27 11:32 UTC, FYMG commented
search это отдельная сущность, вынеси его из shared

2024-08-28 22:37 UTC, kvaker commented on train-a/src/app/shared/services/search.service.ts
> +    return this.http.get<SearchResult>(this.apiUrl, { params }).pipe(
Почему-то твои комментарии не приходили на почту. Не видел этот комментарий. Постараюсь учесть

2024-08-29 12:20 UTC, AngelinaBz commented on train-a/src/app/core/components/header/header.component.html
> +    </div>
повторюсь, что это не надо, так как компоненты выводятся через router-outlet

2024-08-29 12:20 UTC, AngelinaBz commented on train-a/src/app/shared/pages/home/search-results/search-results.component.html
> +              <span>Women Only</span>
Ты берешь какие-то классы по умолчанию (1st, 2nd, Women Only), но их нет в ответе. Нужно показывать места в вагонах, которые получаем из ответа. Посмотри, пожалуйста, еще раз Response.

2024-08-29 12:20 UTC, AngelinaBz commented on train-a/src/app/shared/pages/home/search-results/search-results.component.ts
> +    const count = { carriage1: 0, carriage2: 0, carriage3: 0 };
а если классов вагонов больше, чем три? Или в этом маршруте нет какого-то из вагонов? Опять же посмотри на Response.

2024-08-29 12:20 UTC, AngelinaBz commented on train-a/src/app/shared/pages/home/search-results/search-results.component.ts
> +    });
здесь тоже фиксированное кол-во классов вагонов

2024-08-29 12:21 UTC, AngelinaBz commented
Route выводится неправильно. Станции повторяются 
<img width="1215" alt="Снимок экрана 2024-08-29 в 14 54 23" src="https://github.com/user-attachments/assets/20de9dfd-3cbf-4587-b70d-f0036aab34d8">

2024-08-29 14:59 UTC, kvaker commented on train-a/src/app/shared/pages/home/search-results/search-results.component.ts
> +    });
Разбираюсь. Эти api/route api/carriage api/station... Крышу сносит...

2024-08-29 15:11 UTC, FYMG commented
А зачем ты диалог делать начал? #6 за мной закреплена

2024-08-29 19:48 UTC, kvaker commented
Уже увидел. Твой пул реквест... Как начал https://github.com/rolling-scopes-school/tasks/blob/master/tasks/train-a/search.md так и продолжал. Не досмотрел. Смотрю ты разобрался с запросами и получением данных api/route api/carriage api/station

2024-09-02 22:07 UTC, FYMG requested changes

2024-09-02 22:07 UTC, FYMG commented on train-a/src/app/search/components/search-results/search-results.component.html
> +                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
Вставляй иконки через mat-icons https://fonts.google.com/icons https://material.angular.io/components/icon/overview

2024-09-02 22:07 UTC, FYMG commented on train-a/src/app/search/components/search-results/search-results.component.ts
> +  private getCarriageType(carriageCode: CarriageCode): CarriageItem {
Есть сервис для получения этого в Carriage state

2024-09-02 22:07 UTC, FYMG commented on train-a/src/app/search/components/search-results/search-results.component.ts
> +        if (carriageCode === 'carriage1') seatCounts.carriage1 += freeSeats;
Переделай, у нас carriage с сервера беруться

2024-09-02 22:07 UTC, FYMG commented on train-a/src/app/shared/components/route-dialog/route-dialog.component.html
Файл не используется, можно удалять

2024-09-02 22:07 UTC, FYMG commented on train-a/src/app/shared/configs/paths.ts
> +  main: 'home',
Home Page
Browser path: /

2024-09-02 22:07 UTC, FYMG commented on train-a/src/app/shared/models/search.models.ts
> +export interface StationInfo {
Это есть в одноименных сервисах, используй готовые

2024-09-02 22:07 UTC, FYMG commented on train-a/src/app/shared/models/trip.models.ts
> +  wagons: Wagon[];
Используй названия, как в апи

2024-09-02 22:07 UTC, FYMG commented on train-a/src/app/shared/services/search.service.ts
> +  search(criteria: SearchCriteria): Observable<SearchResult> {
Используй state с effect(ами)

2024-09-02 22:07 UTC, FYMG commented on train-a/src/app/shared/services/search.service.ts
> +}
Используй готовое

2024-09-02 22:07 UTC, FYMG commented on train-a/src/assets/img/svg/logo.svg
Используй svg из библиотеки

2024-09-04 13:32 UTC, MaruyYak approved these changes

2024-09-04 14:44 UTC, AngelinaBz approved these changes

2024-09-04 14:52 UTC, MaruyYak approved these changes

2024-09-04 15:27 UTC, AngelinaBz approved these changes

2024-09-04 15:50 UTC, FYMG commented
У тебя есть нормально сделанная карточка, зачем ты данные которое должны быть в каточке перенес в result?

2024-09-04 15:53 UTC, FYMG commented
Не до конца понимаю, что у тебя происходит с вагонами, у тебя есть список типов вагонов в carriages там есть имя, код, бери оттуда, а не хардкодь

2024-09-04 18:27 UTC, FYMG approved these changes

2024-09-04 19:10 UTC, merged