User order page
AngelinaBz/train-a pull request #25
Opened 2024-08-28 19:06 UTC by AngelinaBz

### U.P. Create My orders Page
**Screenshot:** (optional)
![orders](https://github.com/user-attachments/assets/6d1a1374-15d9-4c7c-ba9f-0a97317b85fc)

Rationale: 

- Created an Order page for the User.
- It displayed all the user's orders, including information: the start trip station, start trip time, end trip station, end trip time, trip duration, carriage type, seat number, car number and price.
- Sorted by the start time of the trip in ascending order.
- Added a `Cancel` button for Active orders. 

!!! Styles will be added as part of the [task](https://github.com/users/AngelinaBz/projects/1/views/1?pane=issue&itemId=77171232)
!!! Orders Page for the Admin will be implemented as part of the [task](https://github.com/users/AngelinaBz/projects/1/views/1?pane=issue&itemId=76291257)
!!! The ApiService and App component changes are added only for testing orders. They will be deleted.

2024-08-29 16:40 UTC, FYMG requested changes
Токены нужно поправить, их недолжны быть нигде кроме auth сервиса

2024-08-29 16:40 UTC, FYMG commented on train-a/src/app/orders/components/order-card/order-card.component.ts
> +    this.authFacade.authToken$.subscribe((token) => {
А зачем? У тебя по умолчанию токен есть, тк страница приватная и он пробрасывается в интерцепторе.

2024-08-29 16:40 UTC, FYMG commented on train-a/src/app/orders/components/order-card/order-card.component.ts
> +      if (result && this.token) {
опять же токен

2024-08-29 16:40 UTC, FYMG commented on train-a/src/app/orders/components/order-card/order-card.component.ts
> +      this.formattedStartTime = this.datePipe.transform(this.startTime, 'MMMM dd, HH:mm')!;
Используй пайпы в шаблоне

2024-08-29 17:40 UTC, AngelinaBz commented on train-a/src/app/orders/components/order-card/order-card.component.ts
> +    this.authFacade.authToken$.subscribe((token) => {
В этой ветке еще не было интерцептора. Обновилась, спасибо.

2024-08-29 17:40 UTC, AngelinaBz commented on train-a/src/app/orders/components/order-card/order-card.component.ts
> +      if (result && this.token) {
обновила

2024-08-29 17:41 UTC, AngelinaBz commented on train-a/src/app/orders/components/order-card/order-card.component.ts
> +      this.formattedStartTime = this.datePipe.transform(this.startTime, 'MMMM dd, HH:mm')!;
перенесла в шаблон, спасибо

2024-08-30 06:16 UTC, FYMG approved these changes
👍

2024-08-30 11:13 UTC, MaruyYak approved these changes

2024-08-30 11:32 UTC, merged